name: Deploy Angular App

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check the source code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configure Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Node.js version compatible with Angular

    # 3. Install dependencies
    - name: Install dependencies
      run: npm install

    # 4. Build the Angular application
    - name: Build Angular app
      run: npm run build -- --configuration production

    # 5. Deploy to the FTP server
    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }} # FTP server address
        username: ${{ secrets.FTP_USERNAME }} # FTP username
        password: ${{ secrets.FTP_PASSWORD }} # FTP password
        local-dir: dist/evendev.net/browser/ # Local directory to upload
        server-dir: /public_html/ # Target directory on the server
