name: Deploy Angular App

on:
  push:
    branches:
      - main # Déclenche le workflow sur les changements de la branche main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifiez le code source
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurez Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Version de Node.js compatible avec Angular

    # 3. Installez les dépendances
    - name: Install dependencies
      run: npm install

    # 4. Construisez l'application Angular
    - name: Build Angular app
      run: npm run build -- --configuration production

    # 5. Déployez sur le serveur FTP
    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }} # Adresse du serveur FTP
        username: ${{ secrets.FTP_USERNAME }} # Nom d'utilisateur FTP
        password: ${{ secrets.FTP_PASSWORD }} # Mot de passe FTP
        local-dir: dist/evendev.net/browser/ # Dossier local à téléverser
        server-dir: /public_html/ # Dossier cible sur le serveur
